#ifndef LIMITS_H_INCLUDED
#define LIMITS_H_INCLUDED

#define MAX_RECV_BUFFER     4096
#define MAX_MESSAGE_BUFFER  420
#define MAX_TIMERS          4
#define MAX_INVENTORY_SLOTS 25
#define MAX_MONSTERS        40
//Seconds
#define WEATHER_INTERVAL    3600
#define HEALING_INTERVAL    1800
#define SAVING_INTERVAL     900
#define BATTLE_INTERVAL     1800

#endif
